{'merchant': {'id': 'INTEGER,', 'merchant': 'VARCHAR(128),'},
 'ram_prod': {'id': 'INTEGER,',
              'manufacturer': 'VARCHAR(128),',
              'ram_name': 'VARCHAR(128),',
              'memory_type': 'VARCHAR(128),',
              'speed': 'INTEGER,',
              'capacity': 'INTEGER,'},
 'time': {'id': 'SERIAL,',
          'year': 'INTEGER,',
          'month': 'INTEGER,',
          'day': 'INTEGER,',
          'week': 'INTEGER,'},
 'region': {'id': 'INTEGER,',
            'code': 'VARCHAR(128),',
            'currency': 'VARCHAR(128),'},
 'cpu_price': {'id': 'SERIAL,',
               'cpu_prod_id': 'INTEGER REFERENCES cpu_prod(id) ON DELETE CASCADE,',
               'time_id': 'INTEGER REFERENCES time(id) ON DELETE CASCADE,',
               'region_id': 'INTEGER REFERENCES region(id) ON DELETE CASCADE,',
               'merchant_id': 'INTEGER REFERENCES merchant(id) ON DELETE '
                             'CASCADE,',
               'price_usd': 'NUMERIC(20,2),',
               'price_original': 'NUMERIC(20,2),'},
 'crypto_data': {'id': 'INTEGER,',
                 'code': 'VARCHAR(128)',
                 'currency_name': 'VARCHAR(128),',
                 'is_mineable': 'BOOLEAN NOT NULL,'},
 'ram_price': {'id': 'SERIAL,',
               'ram_prod_id': 'INTEGER REFERENCES ram_prod(id) ON DELETE CASCADE,',
               'time_id': 'INTEGER REFERENCES time(id) ON DELETE CASCADE,',
               'region_id': 'INTEGER REFERENCES region(id) ON DELETE CASCADE,',
               'merchant_id': 'INTEGER REFERENCES merchant(id) ON DELETE '
                             'CASCADE,',
               'price_usd': 'NUMERIC(20,2),',
               'price_original': 'NUMERIC(20,2),'},
 'gpu_prod': {'id': 'INTEGER',
              'processor_manufacturer': 'VARCHAR(128),',
              'processor': 'VARCHAR(128),',
              'gpu_manufacturer': 'VARCHAR(128),',
              'memory_capacity': 'INTEGER,',
              'memory_type': 'VARCHAR(128),'},
 'cpu_prod': {'id': 'INTEGER',,
              'manufacturer': 'VARCHAR(128),',
              'series': 'VARCHAR(128),',
              'cpu_name': 'VARCHAR(128),',
              'cores': 'INTEGER,',
              'socket': 'VARCHAR(128),'},
 'gpu_price': {'id': 'SERIAL',
               'gpu_prod_id': 'INTEGER REFERENCES gpu_prod(id) ON DELETE CASCADE,',
               'time_id': 'INTEGER REFERENCES time(id) ON DELETE CASCADE,',
               'region_id': 'INTEGER REFERENCES region(id) ON DELETE CASCADE,',
               'merchant_id': 'INTEGER REFERENCES merchant(id) ON DELETE '
                             'CASCADE,',
               'price_usd': 'NUMERIC(20,2),',
               'price_original': 'NUMERIC(20,2),'},
 'crypto_rate': {'id': 'SERIAL',
                 'code_id': 'INTEGER REFERENCES code(id) ON DELETE CASCADE,',
                 'time_id': 'INTEGER REFERENCES time(id) ON DELETE CASCADE,',
                 'open': 'NUMERIC(20,2),',
                 'close': 'NUMERIC(20,2),',
                 'high': 'INTEGER,',
                 'low': 'NUMERIC(20,2),'}}